### ISSUE TITLE
the   nodeHandle_.param("camera_params_yaml", cameraParamsFile, string("/home/mav-lab/intrinsic.yaml")); 

### ISSUE THREAD

**Issue by xiaowei520-lwl** [ZJU-Robotics-Lab/GEM#10]
can you give me the yaml file ? i run the code but in the terminal make the mistakes.
ERROR: Wrong path to settings
[elevation_mapping_0-2] process has died [pid 5692, exit code -11, cmd /home/lwl/GEM-map/devel/lib/elevation_mapping/elevation_mapping /voxel_grid/output:=/robot0/pointcloud /stereo_grey/left/image_raw:=/robot0/image_rect __name:=elevation_mapping_0 __log:=/home/lwl/.ros/log/6eb9a3cc-4f61-11ec-8e95-00d86184c4c3/elevation_mapping_0-2.log].
log file: /home/lwl/.ros/log/6eb9a3cc-4f61-11ec-8e95-00d86184c4c3/elevation_mapping_0-2*.log

**Comment by MaverickPeter** [comment]
@rosliwanlei  Hi, you can change this path to this "https://github.com/ZJU-Robotics-Lab/GEM/blob/main/elevation_mapping/yq_intrinsic.yaml", it's already uploaded in this repo.
