### ISSUE TITLE
Questions about the visualization

### ISSUE THREAD

**Issue by zhanghua7099** [ZJU-Robotics-Lab/GEM#11]
Hi! Thank you for your good work.

I built this project, but the visualization may have some problems for my computer. I use your provided `test.bag`, but I only get odometry results. The point clouds didn't have any visualization. The rviz received the pcd message, but it can't output it.

![2021-12-01 16-08-19 的屏幕截图](https://user-images.githubusercontent.com/28104987/144195912-c07331d5-c71f-4fce-95a1-1cf8c14b8bce.png)

Could you please tell me how to fix this bug?
I use Ubuntu 20.04 with ROS noetic.

**Comment by zhanghua7099** [comment]
By the way, can you provide some details about running KITTI dataset like your demo videos?

**Comment by MaverickPeter** [comment]
Hi!@zhanghua7099 Thanks for following our work.
Is there any output in the GEM terminal? Can you provide a screenshot of the terminal? I'll try to find out what happened.

**Comment by zhanghua7099** [comment]
I try to debug it through `rostopic echo /elevation_mapping_0/robot0/visual_map`. This topic didn't publish any messages. The similar situation occurs at these topics:
![2021-12-02 16-08-49 的屏幕截图](https://user-images.githubusercontent.com/28104987/144382993-25b9463c-5aea-4452-ae43-7acf3273b652.png)

After I run the command:
`roslaunch elevation_mapping_demos simple_demo.launch`
![2021-12-02 16-14-03 的屏幕截图](https://user-images.githubusercontent.com/28104987/144383270-bd087274-7c4d-49df-8212-63b781b60695.png)

This may be the reason why the elevation map is not displayed.

**Comment by zhanghua7099** [comment]
The point cloud of the lidar sensor can be visualized in rviz.

**Comment by MaverickPeter** [comment]
@zhanghua7099 
You can return to the commit a359d011bf5f11e26cf0e330ecc4a3e82f590a76. I'll try to fix this bug ASAP.

**Comment by zhanghua7099** [comment]
I have tried the commit a359d01. It still has similar errors.

Thank you for helping me!

**Comment by zhanghua7099** [comment]
In the commit a359d01, the error message will be printed after I play the rosbag.

In the current commit, the error message will be printed after I run the command directly:
`roslaunch elevation_mapping_demos simple_demo.launch`

**Comment by MaverickPeter** [comment]
Hi @zhanghua7099 
I test the newest version on my own computer, there is some problem with the rviz plugins, you may discard the rviz line in the launch file, I'll try to figure out the rviz problem ASAP.

**Comment by zhanghua7099** [comment]
Hi!

Thank you for your hard work. I have tried the new version. After I change the launch file, the code can be run. 

Unfortunately, the updated version still has some errors related to CUDA programming:
`addKernel launch failed: an illegal memory access was encountered
`

I didn't know what's wrong with my computer. I use CUDA 11.3 with cudnn 8.2.

![2021-12-04 18-53-14 的屏幕截图](https://user-images.githubusercontent.com/28104987/144706878-2e9a6538-0ea0-4dfb-9d12-f1c046b4ad4f.png)

**Comment by MaverickPeter** [comment]
@zhanghua7099  You can try to reboot the machine. If it doesn't work, you may have to change the parameters in filter_kitti.launch to downsample the point cloud to  < 20000 points.

**Comment by zhanghua7099** [comment]
Hi!
I changed the compilation options of CUDA. This CUDA error could be solved. 

https://github.com/ZJU-Robotics-Lab/GEM/blob/e72fba4a0d6c168e4fa2ff46e625ca3e07051656/elevation_mapping/elevation_mapping/cuda/CMakeLists.txt#L7

Just change the arch and code of the GPU can solve this error:
`SET(CUDA_NVCC_FLAGS ${CUDA_NVCC_FLAGS};-O3;-std=c++14 -gencode arch=compute_86,code=sm_86)
`

By the way, I recommend adding C++14 to all CmakeLists files if using PCL. 

Thanks a lot!

**Comment by MaverickPeter** [comment]
@leslieburke 
Hi, can you paste the complete error information, it may appear at the beginning of the build process.
