### ISSUE TITLE
the question about costmap !!

### ISSUE THREAD

**Issue by xiaowei520-lwl** [ZJU-Robotics-Lab/GEM#12]
i run the code about create_globalmap.launch file and the read the code .but i have two questions about it .
1.elevationMap_layer.cpp **bool is_obstacle = (data(gindex(0), gindex(1)) <0.7);** the value in the data is elevation ? what is  **the value  and index**    the correspondence relationship  ? and index[0],index[1] corresponding what ?
2. why the data is <0.7  ? the high value of elevation should obstacles?

**Comment by MaverickPeter** [comment]
Hi @xiaowei520-lwl
1. the data() is defined before data = elevation_map_["traver"], the data represent traversability. The index here is related to the gridmap index. 
2. the 0.7 is a traversability threshold, I move it to the parameter yaml file in the newest version.

**Comment by xiaowei520-lwl** [comment]
the 2 question is that i want to know about why is < the threshold.it should be > the threshold? because, i think the high value  of elevation  the low traversability ? Am i understanding correctly？Thank you very much!

**Comment by MaverickPeter** [comment]
@xiaowei520-lwl
The data here represents traversability calculated by elevation but not the original elevation, so the threshold is the original threshold. One can easily get different attributes by this operation, "data = elevation_map_["xxx"]", here we get traver means the traversability, you can change it to "data = elevation_map_["elevation"]" or "data = elevation_map_["slope"]" to get other information in the gridmap.
