### ISSUE TITLE
about costmap

### ISSUE THREAD

**Issue by TT22TY** [ZJU-Robotics-Lab/GEM#18]
Thank you for your great work!
I tried with the simple demo in the newest version with "roslaunch pointMap_layer create_globalmap.launch", but it seems that the topic about costmap ( /move_base/global_costmap/costmap and /move_base/local_costmap/costmap） haven't published. 
I was wondering whether I missed something.
Thanks！

**Comment by MaverickPeter** [comment]
@TT22TY  Have you encountered this report in costmap terminal? 
 _"Warning: Invalid argument "/robot0/map" passed to canTransform argument target_frame in tf2 frame_ids cannot start with a '/' like: "_
This is caused by the different versions of ROS, you can delete '/' in the params file which I've already updated in the new version of GEM. You can check it.

**Comment by MaverickPeter** [comment]
@TT22TY  You may change the param https://github.com/ZJU-Robotics-Lab/GEM/blob/099e3a6b972d21d698c3c2bffa2951c786d6704a/layers/params/global_costmap_params.yaml#L12 to true and try it again

**Comment by TT22TY** [comment]
@MaverickPeter  Thanks!

**Comment by TT22TY** [comment]
@MaverickPeter I have another issue. I try with my dataset(only contains lidar points and /tf)，I use the 'fake_img.py' to generate the fake image. 
The topic for lidar and image have the same timestamp, as figure 1 shows. I did not use --clock to play the bag, and also set the use_sim_time = false. However, the simple_demos.launch occurs the problem as picture 2 shows,  I was wondering how to solve the problem. 
Thanks!

<img width="270" alt="1" src="https://user-images.githubusercontent.com/20963873/165050350-642befae-5b8e-4cf0-8a5d-a869ab266c19.png">

![2](https://user-images.githubusercontent.com/20963873/165050386-17e56aaf-13d5-4851-aed4-3d31fa12b672.png)

**Comment by TT22TY** [comment]
@MaverickPeter Thanks！
