### ISSUE TITLE
fatal error: dislam_msgs/SubMap.h: No such file or directory

### ISSUE THREAD

**Issue by NancyHu3245** [ZJU-Robotics-Lab/GEM#2]
Hi, thanks for your amazing work!
I have the following issue when l use "catkin_make":
include/elevation_mapping/ElevationMapping.hpp:21:10: fatal error: dislam_msgs/SubMap.h: No such file or directory
 #include "dislam_msgs/SubMap.h"
          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In the workspace,I didn't find SubMap.h. So,I really appreciate your help.

**Comment by MaverickPeter** [comment]
Hi, Nancy, I'm sorry for the missing files, I'll update now.

**Comment by MaverickPeter** [comment]
You may reclone the repository for updates. I further check the validation of the files and made some changes.

**Comment by NancyHu3245** [comment]
Thank you.

**Comment by MaverickPeter** [comment]
Hi, @gilhant49  I'm not sure about this issue of catkin build, it may be caused by the isolated build chains. You may try to catkin build the repo again to include the submap.h in the build chain. If it cannot solve the issue, I suggest using catkin_make to build the repo.
