### ISSUE TITLE
How to get the demo bag, the download link doesn't seem to work

### ISSUE THREAD

**Issue by JACKLiuDay** [ZJU-Robotics-Lab/GEM#21]
Hi, thank you for your great work. I want to try GEM with the demo bag or kitti bag. But the download link dosen't seem to work.

**Comment by MaverickPeter** [comment]
@JACKLiuDay  Sorry for the late reply, I've updated REAMDE and add baidupan links.

**Comment by JACKLiuDay** [comment]
> @JACKLiuDay Sorry for the late reply, I've updated REAMDE and add baidupan links.

Thank you so much for your reply.
