### ISSUE TITLE
About using only lidar to do the GEM

### ISSUE THREAD

**Issue by TT22TY** [ZJU-Robotics-Lab/GEM#3]
Thanks for your work, it is amazing!

I noticed that in the README.md, the Subscribed Topics includes :
              /points (sensor_msgs/PointCloud2)
                      The distance measurements. Modify it in launch/simple_demo.launch
              /tf (tf/tfMessage)
                      The transformation tree.

I also read your paper, I was wondering that how to use lidar ( such as in your YQ data set example) to do the GEM, since I noticed that you subscribed the camera topic in your codes. Has the code using only lidar been not released yet?

Thank you!

**Comment by wzy012** [comment]
hello,you run the package GEM successfully?

**Comment by MaverickPeter** [comment]
> Thanks for your work, it is amazing!
> 
> I noticed that in the README.md, the Subscribed Topics includes :
> /points (sensor_msgs/PointCloud2)
> The distance measurements. Modify it in launch/simple_demo.launch
> /tf (tf/tfMessage)
> The transformation tree.
> 
> I also read your paper, I was wondering that how to use lidar ( such as in your YQ data set example) to do the GEM, since I noticed that you subscribed the camera topic in your codes. Has the code using only lidar been not released yet?
> 
> Thank you!

Thanks for following our work.
Sorry for the late reply. We have different versions for different sensor configurations and the code using only lidar has not been released yet. We'll upload it ASAP (hopefully this month).

**Comment by MaverickPeter** [comment]
> Thanks for your work, it is amazing!
> 
> I noticed that in the README.md, the Subscribed Topics includes :
> /points (sensor_msgs/PointCloud2)
> The distance measurements. Modify it in launch/simple_demo.launch
> /tf (tf/tfMessage)
> The transformation tree.
> 
> I also read your paper, I was wondering that how to use lidar ( such as in your YQ data set example) to do the GEM, since I noticed that you subscribed the camera topic in your codes. Has the code using only lidar been not released yet?
> 
> Thank you!

Hi, we have released our lidar-only version. 
We'll integrate this version into our main branch in the future.
Thanks for following our work.

**Comment by TT22TY** [comment]
> > Thanks for your work, it is amazing!
> > I noticed that in the README.md, the Subscribed Topics includes :
> > /points (sensor_msgs/PointCloud2)
> > The distance measurements. Modify it in launch/simple_demo.launch
> > /tf (tf/tfMessage)
> > The transformation tree.
> > I also read your paper, I was wondering that how to use lidar ( such as in your YQ data set example) to do the GEM, since I noticed that you subscribed the camera topic in your codes. Has the code using only lidar been not released yet?
> > Thank you!
> 
> Hi, we have released our lidar-only version.
> We'll integrate this version into our main branch in the future.
> Thanks for following our work.

Thank you very much! I just tried it with test.bag, with the result that the topic of "/opt_map" can not be published successfully. I notice it is the line 876 in “ElevationMapping.cpp", I have not figured it out.  
Looking forward to the full version~

**Comment by MaverickPeter** [comment]
> > > Thanks for your work, it is amazing!
> > > I noticed that in the README.md, the Subscribed Topics includes :
> > > /points (sensor_msgs/PointCloud2)
> > > The distance measurements. Modify it in launch/simple_demo.launch
> > > /tf (tf/tfMessage)
> > > The transformation tree.
> > > I also read your paper, I was wondering that how to use lidar ( such as in your YQ data set example) to do the GEM, since I noticed that you subscribed the camera topic in your codes. Has the code using only lidar been not released yet?
> > > Thank you!
> > 
> > 
> > Hi, we have released our lidar-only version.
> > We'll integrate this version into our main branch in the future.
> > Thanks for following our work.
> 
> Thank you very much! I just tried it with test.bag, with the result that the topic of "/opt_map" can not be published successfully. I noticed that it is the line 876 in “ElevationMapping.cpp", I have not figured it out.
> Looking forward to the full version.

The "/opt_map" is a debug msg for loop closing rectify which is not released in this version. You can simply ignore it.

**Comment by TT22TY** [comment]
> > > > Thanks for your work, it is amazing!
> > > > I noticed that in the README.md, the Subscribed Topics includes :
> > > > /points (sensor_msgs/PointCloud2)
> > > > The distance measurements. Modify it in launch/simple_demo.launch
> > > > /tf (tf/tfMessage)
> > > > The transformation tree.
> > > > I also read your paper, I was wondering that how to use lidar ( such as in your YQ data set example) to do the GEM, since I noticed that you subscribed the camera topic in your codes. Has the code using only lidar been not released yet?
> > > > Thank you!
> > > 
> > > 
> > > Hi, we have released our lidar-only version.
> > > We'll integrate this version into our main branch in the future.
> > > Thanks for following our work.
> > 
> > 
> > Thank you very much! I just tried it with test.bag, with the result that the topic of "/opt_map" can not be published successfully. I noticed that it is the line 876 in “ElevationMapping.cpp", I have not figured it out.
> > Looking forward to the full version.
> 
> The "/opt_map" is a debug msg for loop closing rectify which is not released in this version. You can simply ignore it

Thank you~

**Comment by TT22TY** [comment]
> hello,you run the package GEM successfully?

Sorry, I missed your message.
In fact, I have not run the GEM successfully with camera+lidar on the test.bag the author provided. How about you?

@MaverickPeter hello, I tried to test the main branch with test.bag on lidar+camera, but it seems that it gets stuck in the composingGlobalMap function, with globalMap_.size()=0.
![WechatIMG1](https://user-images.githubusercontent.com/20963873/124568641-b4c1b400-de77-11eb-8664-f3d0927bf66d.png)
Besides, I looked into the code, I was wondering where are the "denseSignal" and "map saving Signal" published.
Could you give me some guide to deal with this issue?

Last but not least, looking forward to the merged version for both lidar-only and camera+lidar.

Thank you very much.
