### ISSUE TITLE
how to make the package run successfully

### ISSUE THREAD

**Issue by wzy012** [ZJU-Robotics-Lab/GEM#4]
Hi,
In ETH package,usr needs to provide pointcloud(input source file) and pose,But in this package,I want to know the node (elevation_mapping_0) is subscribe lidar pointcloud and pose?
I modifly the config file,rviz is nothing,can you give me some suggestions?
Thanks!

**Comment by MaverickPeter** [comment]
> Hi,
> In ETH package,usr needs to provide pointcloud(input source file) and pose,But in this package,I want to know the node (elevation_mapping_0) is subscribe lidar pointcloud and pose?
> I modifly the config file,rviz is nothing,can you give me some suggestions?
> Thanks!

Hi, in this branch of GEM, we only support the configuration of lidar+camera. It may cause the problem you encountered.

**Comment by MaverickPeter** [comment]
I'll upload a rosbag for tests.

**Comment by wzy012** [comment]
THANKS！
it must use lidar+camera ?

**Comment by wzy012** [comment]
> I'll upload a rosbag for tests.

Thanks!
it is must use lidar+camera?

**Comment by MaverickPeter** [comment]
> > I'll upload a rosbag for tests.
> 
> Thanks!
> it is must use lidar+camera?

For today's update, yes.
only lidar and stereo versions will update later.

**Comment by wzy012** [comment]
> > > I'll upload a rosbag for tests.
> > 
> > Thanks!
> > it is must use lidar+camera?
> 
> For today's update, yes.
> only lidar and stereo versions will update later.

OK！
I'm looking forward to it!
Thanks for your contribution!
