### ISSUE TITLE
get stuck in th composingGlobalMap

### ISSUE THREAD

**Issue by TT22TY** [ZJU-Robotics-Lab/GEM#5]
@MaverickPeter hello, I tried to test the main branch with test.bag on lidar+camera, but it seems that it gets stuck in the composingGlobalMap function, with globalMap_.size()=0.
![WechatIMG1](https://user-images.githubusercontent.com/20963873/124568641-b4c1b400-de77-11eb-8664-f3d0927bf66d.png)
Besides, I looked into the code, I was wondering where are the "denseSignal" and "map saving Signal" published.
Could you give me some guide to deal with this issue?

Last but not least, looking forward to the merged version for both lidar-only and camera+lidar.

Thank you very much.

_Originally posted by @TT22TY in https://github.com/ZJU-Robotics-Lab/GEM/issues/3#issuecomment-874620567_

**Comment by MaverickPeter** [comment]
@TT22TY  Hi, the dense mapping signal and map saving signal are interfaces for other nodes, or you can simply publish it in your terminal by rostopic pub. As for the test.bag with the lidar-camera mapping, I suggest using a voxel filter nodelet to downsample the point cloud first. Also, I'll try to reproduce this problem ASAP.

**Comment by TT22TY** [comment]
> @TT22TY Hi, the dense mapping signal and map saving signal are interfaces for other nodes, or you can simply publish it in your terminal by rostopic pub. As for the test.bag with the lidar-camera mapping, I suggest using a voxel filter nodelet to downsample the point cloud first. Also, I'll try to reproduce this problem ASAP.

Thank you very much!

**Comment by TT22TY** [comment]
> @TT22TY Hi, the dense mapping signal and map saving signal are interfaces for other nodes, or you can simply publish it in your terminal by rostopic pub. As for the test.bag with the lidar-camera mapping, I suggest using a voxel filter nodelet to downsample the point cloud first. Also, I'll try to reproduce this problem ASAP.

Hello, after using a voxel filter to downsample first, as well as publish the dense mapping signal and map saving signal in terminal by rostopic pub, the problem still exists.

**Comment by MaverickPeter** [comment]
Hi @TT22TY, can you run gem without any signal (especially saving signal) and show the issue screenshot for me? The map saving signal is not available at the very beginning of the mapping process.

**Comment by TT22TY** [comment]
> Hi @TT22TY, can you run gem without any signal (especially saving signal) and show the issue screenshot for me? The map saving signal is not available at the very beginning of the mapping process.

OK, the issue screenshot without any signal publish by myself is as below( I just output the globalMap_.size() at the beginning of the "composingGlobalMap" function to try to track the issue):
![1](https://user-images.githubusercontent.com/20963873/124855329-6299a380-dfdb-11eb-8e88-a2e6ac8fd3e9.jpeg)
![2](https://user-images.githubusercontent.com/20963873/124855334-64636700-dfdb-11eb-9e92-fc13655898d8.png)
![3](https://user-images.githubusercontent.com/20963873/124855343-675e5780-dfdb-11eb-9835-2ce28a7fd77c.jpeg)

**Comment by MaverickPeter** [comment]
Hi @TT22TY , I have figured it out. One flag is not initialized, I have correct it in the released main branch, you can now run it without this issue.

**Comment by TT22TY** [comment]
> Hi @TT22TY , I have figured it out. One flag is not initialized, I have correct it in the released main branch, you can now run it without this issue.

Thank you! @MaverickPeter
